image: Ubuntu1804 # образ для сборки

stack: node 14 # окружение

branches:
  only:
    - master # ветка git

cache: node_modules # кеширование

install:
  - npm install # команда установки зависимостей
  - npm install pm2 -g

build: off # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build # команда сборки
  - pm2 --name HelloWorld start npm -- start

test_script:
  - npm run lint && npm test # скрипт тестирования
  - npm run e2e # скрипт тестирования e2e
  - pm2 delete 0 # убить сервер

deploy_script: # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
